// Generated by CoffeeScript 1.10.0
(function() {
  var menu;

  menu = {
    'file': {
      'save': console.log('saved!'),
      'recents': {
        'foo': (function(_this) {
          return function() {
            return console.log('foo!');
          };
        })(this),
        'bar': (function(_this) {
          return function() {
            return console.log('bar!');
          };
        })(this),
        'baz': (function(_this) {
          return function() {
            return console.log('baz!');
          };
        })(this)
      }
    },
    'edit': {
      'undo': (function(_this) {
        return function() {
          return console.log('undo!');
        };
      })(this),
      'redo': (function(_this) {
        return function() {
          return console.log('redo!');
        };
      })(this)
    }
  };

  window.addEventListener('DOMContentLoaded', (function(_this) {
    return function() {
      return console.log('loaded!');
    };
  })(this));

}).call(this);
